- request:
    url: ^/cards/?$
    method: GET
  response:
    status: 200
    headers:
      Content-Type: application/json
      Link: <https://api.magicthegathering.io/v1/cards/?page=2>; rel="last", <https://api.magicthegathering.io/v1/cards/?page=2>; rel="next"
    file: json/cards/all.json

- request:
    url: ^/cards/?&page=2
    method: GET
  response:
    status: 200
    headers:
      Content-Type: application/json
    file: json/cards/allPage2.json

- request:
    url: ^/cards/1/?$
    method: GET
  response:
    status: 200
    headers:
      Content-Type: application/json
    file: json/cards/1.json

- request:
    url: ^/cards/10/?$
    method: GET
  response:
    status: 200
    headers:
      Content-Type: application/json
    file: json/cards/10.json
    
- request:
    url: ^/cards/8a5d85644f546525433c4472b76c3b0ebb495b33/?$
    method: GET
  response:
    status: 200
    headers:
      Content-Type: application/json
    file: json/cards/8a5d85644f546525433c4472b76c3b0ebb495b33.json

- request:
    url: ^/cards/926234c2fe8863f49220a878346c4c5ca79b6046/?$
    method: GET
  response:
    status: 200
    headers:
      Content-Type: application/json
    file: json/cards/926234c2fe8863f49220a878346c4c5ca79b6046.json

- request:
    url: ^/cards/-1/?$
    method: GET
  response:
    status: 404
    headers:
      Content-Type: application/json
    body: >
      {"status":"404","error":"Not Found"}

- request:
    url: ^/types/?$
    method: GET
  response:
    status: 200
    headers:
      Content-Type: application/json
    file: json/types/types.json

- request:
    url: ^/supertypes/?$
    method: GET
  response:
    status: 200
    headers:
      Content-Type: application/json
    file: json/types/supertypes.json

- request:
    url: ^/subtypes/?$
    method: GET
  response:
    status: 200
    headers:
      Content-Type: application/json
    file: json/types/subtypes.json

- request:
    url: ^/sets/?$
    method: GET
  response:
    status: 200
    headers:
      Content-Type: application/json
    file: json/sets/all.json

- request:
    url: ^/sets/LEA/?$
    method: GET
  response:
    status: 200
    headers:
      Content-Type: application/json
    file: json/sets/LEA.json
    
- request:
    url: ^/sets/LEB/?$
    method: GET
  response:
    status: 200
    headers:
      Content-Type: application/json
    file: json/sets/LEB.json
    
- request:
    url: ^/sets/666/?$
    method: GET
  response:
    status: 404
    headers:
      Content-Type: application/json
    body: >
      {"status":"404","error":"Not Found"}
      
- request:
    url: ^/sets/KLD/booster/?$
    method: GET
  response:
    status: 200
    headers:
      Content-Type: application/json
    file: json/sets/KLD-booster.json
      
